version: "3.9"

services:
  economic-events-worker:
    build:
      context: .                # Path where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: economic-events-worker
    restart: unless-stopped     # Keeps it running in the background
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    # Uncomment if you need persistent data
    # volumes:
    #   - ./data:/app/data
